steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gateway'
      - '--source=.'
      - '--region=asia-south1'
      - '--allow-unauthenticated'
      - '--set-build-env-vars=BP_JVM_VERSION=21,BP_MAVEN_BUILT_MODULE=gateway'
