steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'show'
      - '--source=.'
      - '--region=${_DEPLOY_REGION}'
      - '--allow-unauthenticated'
      - '--set-build-env-vars=BP_JVM_VERSION=21,BP_MAVEN_BUILT_MODULE=show,BP_MAVEN_BUILD_ARGUMENTS=-pl show -am package -DskipTests'

substitutions:
  _DEPLOY_REGION: asia-south1

options:
  logging: CLOUD_LOGGING_ONLY
