steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'movie'
      - '--source=.'
      - '--region=${_DEPLOY_REGION}'
      - '--allow-unauthenticated'
      - '--set-build-env-vars=BP_JVM_VERSION=21,BP_MAVEN_BUILT_MODULE=movie'

substitutions:
  _DEPLOY_REGION: asia-south1

options:
  logging: CLOUD_LOGGING_ONLY
